version: "3.8"

networks:
  weshare-network:
    driver: bridge

services:
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=weshare
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/my.cnf:/etc/my.cnf
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - weshare-network

  weshare:
    container_name: weshare
    build: .
    environment:
      - DB_USER=root
      - DB_PASSWORD=pwd
      - DB_HOST=mysql
    networks:
      - weshare-network
    depends_on:
      - mysql
      - redis
    ports:
      - "3000:3000"

  redis:
    image: redis:6.0-alpine
    command: redis-server --requirepass ''    
    container_name: redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "6380:6379"
    networks:
      - weshare-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./private/bundle_chained.crt:/etc/ssl/bundle_chained.crt
      - ./private/private.key:/etc/ssl/private.key
    restart: always
    networks:
      - weshare-network
    depends_on:
      - weshare


volumes:
  mysql_data:
